export const TRANSACTION_TYPES = {
  DISBURSEMENT: 1,
  PAYMENT: 2,
  LIQUIDITY_INJECTION: 3,
  REFUND: 4,
}

export const TRANSACTION_CATEGORIES = {
  DISBURSEMENT: 1,
  PAYMENT: 2,
  LIQUIDITY_INJECTION: 3,
  REFUND: 4,
  INTEREST: 10,
}
